// ============================================
// DADOS DO CURSO TEOLOGIA DESCOMPLICADA PARA JOVENS
// LIVRO 5 – CAPÍTULO V - COMO A IGREJA DEVE REAGIR AO PECADO
// ============================================

window.dadosLicao = {
    titulo: "📖 CAPÍTULO V - COMO A IGREJA DEVE REAGIR AO PECADO",
    subtitulo: "Teologia Descomplicada para Jovens - Livro 5, Capítulo 5",
    mapaConfig: {
      centro: [31.0461, 34.8516],
      zoom: 6
    },
  
    listaAparicao: [
      // Abertura
      { numero: 1, referencia: "", tags: "", topico: "📂 Capítulo V", pagina: 86, id: "" },
  
      // 1. Como a Igreja deve se posicionar diante do pecado?
      { numero: 2, referencia: "Gálatas 6.1", tags: "restauração / mansidão / pecador", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Versículo-Chave", pagina: 87, id: "gl6.1" },
      { numero: 3, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Ideia Central", pagina: 87, id: "" },
      { numero: 4, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Explicação Simples e Profunda", pagina: 87, id: "" },
      { numero: 5, referencia: "1 Pedro 1.16", tags: "santidade / imitar deus / chamado", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / a) A Igreja deve confrontar o pecado com fidelidade bíblica", pagina: 87, id: "1pe1.16" },
      { numero: 6, referencia: "1 Coríntios 5.6", tags: "fermento / pecado / contaminação", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / a) A Igreja deve confrontar o pecado com fidelidade bíblica", pagina: 87, id: "1co5.6" },
      { numero: 7, referencia: "Isaías 5.20", tags: "bem / mal / juízo", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / a) A Igreja deve confrontar o pecado com fidelidade bíblica", pagina: 87, id: "is5.20" },
      { numero: 8, referencia: "Tiago 5.16", tags: "confissão / oração / cura", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / b) A Igreja deve orar pela restauração do que caiu", pagina: 88, id: "tg5.16" },
      { numero: 9, referencia: "Gálatas 6.1", tags: "restauração / mansidão / pecador", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / c) A Igreja deve cuidar do pecador com graça", pagina: 88, id: "gl6.1" },
      { numero: 10, referencia: "João 8.11", tags: "pecado / perdão / vai e não peques", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / c) A Igreja deve cuidar do pecador com graça", pagina: 88, id: "jo8.11" },
      { numero: 11, referencia: "Mateus 7.3-5", tags: "julgamento / hipocrisia / trave e argueiro", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / d) A Igreja deve evitar o espírito de julgamento e hipocrisia", pagina: 88, id: "mt7.3-5" },
      { numero: 12, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Perguntas Rápidas dentro da Explicação", pagina: 88, id: "" },
      { numero: 13, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Exemplo Didático", pagina: 89, id: "" },
      { numero: 14, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Exemplo Atual", pagina: 89, id: "" },
      { numero: 15, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Toque de Sabedoria", pagina: 89, id: "" },
      { numero: 16, referencia: "2 Coríntios 2.6-8", tags: "disciplina / perdão / consolação", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Você Sabia?", pagina: 89, id: "2co2.6-8" },
      { numero: 17, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / História Ilustrativa – O Caminho de Volta", pagina: 90, id: "" },
      { numero: 18, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Palavra Pastoral", pagina: 91, id: "" },
      { numero: 19, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Aplicação Prática – Marque suas Respostas", pagina: 91, id: "" },
      { numero: 20, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Tarefa Simples para o Coração", pagina: 91, id: "" },
      { numero: 21, referencia: "", tags: "", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Espaço para Resposta", pagina: 91, id: "" },
  
      // 2. O que acontece quando a Igreja deixa de falar sobre o pecado?
      { numero: 22, referencia: "Isaías 5.20", tags: "bem / mal / juízo", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Versículo-Chave", pagina: 92, id: "is5.20" },
      { numero: 23, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Ideia Central", pagina: 92, id: "" },
      { numero: 24, referencia: "Isaías 5.20", tags: "bem / mal / juízo", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Explicação Simples e Profunda", pagina: 92, id: "is5.20" },
      { numero: 25, referencia: "1 Timóteo 1.15", tags: "cristo veio / salvar / pecadores", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / a) O silêncio sobre o pecado enfraquece a mensagem do evangelho", pagina: 93, id: "1tm1.15" },
      { numero: 26, referencia: "Romanos 3.23", tags: "pecado / glória / todos", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / b) Sem falar sobre pecado, não há arrependimento", pagina: 93, id: "rm3.23" },
      { numero: 27, referencia: "1 Coríntios 5.6", tags: "fermento / pecado / contaminação", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / c) O silêncio sobre o pecado permite que o erro se espalhe", pagina: 93, id: "1co5.6" },
      { numero: 28, referencia: "Ezequiel 33.7-9", tags: "atalaia / alertar / responsabilidade", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / d) Falar sobre o pecado é um ato de amor", pagina: 93, id: "ez33.7-9" },
      { numero: 29, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Perguntas Rápidas dentro da Explicação", pagina: 93, id: "" },
      { numero: 30, referencia: "Romanos 3.23", tags: "pecado / glória / todos", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Perguntas Rápidas dentro da Explicação / 1. O que torna possível o arrependimento?", pagina: 93, id: "rm3.23" },
      { numero: 31, referencia: "Romanos 3.23", tags: "pecado / glória / todos", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Perguntas Rápidas dentro da Explicação / 2. Por que é necessário falar sobre pecado?", pagina: 93, id: "rm3.23" },
      { numero: 32, referencia: "João 1.9", tags: "luz / verdade / ilumina", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Perguntas Rápidas dentro da Explicação / 4. O que acontece quando o pecado é confessado?", pagina: 94, id: "jo1.9" },
      { numero: 33, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Exemplo Didático", pagina: 94, id: "" },
      { numero: 34, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Exemplo Atual", pagina: 94, id: "" },
      { numero: 35, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Toque de Sabedoria", pagina: 94, id: "" },
      { numero: 36, referencia: "Ezequiel 33.7", tags: "atalaia / alertar / responsabilidade", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Você Sabia?", pagina: 94, id: "ez33.7" },
      { numero: 37, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / História Ilustrativa – A Parede Rachada", pagina: 94, id: "" },
      { numero: 38, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Palavra Pastoral", pagina: 95, id: "" },
      { numero: 39, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Aplicação Prática – Marque suas Respostas", pagina: 96, id: "" },
      { numero: 40, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Tarefa Simples para o Coração", pagina: 96, id: "" },
      { numero: 41, referencia: "", tags: "", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Espaço para Resposta", pagina: 96, id: "" },
  
      // 3. A Igreja precisa se adaptar à cultura?
      { numero: 42, referencia: "Romanos 12.2", tags: "não conformar / renovar / vontade de deus", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Versículo-Chave", pagina: 97, id: "rm12.2" },
      { numero: 43, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Ideia Central", pagina: 97, id: "" },
      { numero: 44, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Explicação Simples e Profunda", pagina: 97, id: "" },
      { numero: 45, referencia: "Lucas 4.18-19", tags: "evangelho / libertação / ano aceitável", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 97, id: "lc4.18-19" },
      { numero: 46, referencia: "Tiago 1.27", tags: "religião pura / órfãos / viúvas", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 97, id: "tg1.27" },
      { numero: 47, referencia: "Mateus 5.14-16", tags: "luz / sal / testemunho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 97, id: "mt5.14-16" },
      { numero: 48, referencia: "Mateus 5.16", tags: "boas obras / glorificar / luz", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 98, id: "mt5.16" },
      { numero: 49, referencia: "Mateus 5.13-16", tags: "sal / luz / testemunho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / b) A Igreja deve dialogar com a cultura sem perder seus princípios", pagina: 98, id: "mt5.13-16" },
      { numero: 50, referencia: "Colossenses 4.5-6", tags: "sabedoria / tempo / sal", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / b) A Igreja deve dialogar com a cultura sem perder seus princípios", pagina: 98, id: "cl4.5-6" },
      { numero: 51, referencia: "Hebreus 13.8", tags: "cristo / imutável / ontem e hoje", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / c) A Igreja deve usar meios culturais para comunicar o evangelho", pagina: 98, id: "hb13.8" },
      { numero: 52, referencia: "1 Coríntios 9.22", tags: "fazer-me tudo / salvar / evangelho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / c) A Igreja deve usar meios culturais para comunicar o evangelho", pagina: 98, id: "1co9.22" },
      { numero: 53, referencia: "Jeremias 6.14", tags: "paz / ferida / engano", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "jr6.14" },
      { numero: 54, referencia: "João 15.18-19", tags: "mundo / ódio / escolha", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "jo15.18-19" },
      { numero: 55, referencia: "Atos 17.6-7", tags: "perturbar / mundo / cristo", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "at17.6-7" },
      { numero: 56, referencia: "Atos 3.19", tags: "arrependimento / volta / tempos de refrigério", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "at3.19" },
      { numero: 57, referencia: "1 Pedro 1.15-16", tags: "santidade / chamado / imitar", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "1pe1.15-16" },
      { numero: 58, referencia: "Tiago 4.7", tags: "sujeitar / resistir / diabo", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "tg4.7" },
      { numero: 59, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Perguntas Rápidas dentro da Explicação", pagina: 99, id: "" },
      { numero: 60, referencia: "Mateus 5.14-16", tags: "luz / sal / testemunho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Perguntas Rápidas dentro da Explicação / 1. Qual é a missão da Igreja em relação à cultura?", pagina: 99, id: "mt5.14-16" },
      { numero: 61, referencia: "Marcos 16.15", tags: "ide / evangelho / toda criatura", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Perguntas Rápidas dentro da Explicação / 3. Por que usar meios modernos para evangelizar?", pagina: 99, id: "mc16.15" },
      { numero: 62, referencia: "Atos 3.19", tags: "arrependimento / volta / tempos de refrigério", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Perguntas Rápidas dentro da Explicação / 4. Por que o evangelho confronta a cultura?", pagina: 99, id: "at3.19" },
      { numero: 63, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Exemplo Didático", pagina: 99, id: "" },
      { numero: 64, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Exemplo Atual", pagina: 99, id: "" },
      { numero: 65, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Toque de Sabedoria", pagina: 99, id: "" },
      { numero: 66, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Você Sabia?", pagina: 99, id: "" },
      { numero: 67, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / História Ilustrativa – O Barco na Correnteza", pagina: 100, id: "" },
      { numero: 68, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Palavra Pastoral", pagina: 100, id: "" },
      { numero: 69, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Aplicação Prática – Marque suas Respostas", pagina: 101, id: "" },
      { numero: 70, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Tarefa Simples para o Coração", pagina: 101, id: "" },
      { numero: 71, referencia: "", tags: "", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Espaço para Resposta", pagina: 101, id: "" },
  
      // 4. Como a Igreja pode ser luz no mundo?
      { numero: 72, referencia: "Mateus 5.16", tags: "boas obras / glorificar / luz", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Versículo-Chave", pagina: 102, id: "mt5.16" },
      { numero: 73, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Ideia Central", pagina: 102, id: "" },
      { numero: 74, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Explicação Simples e Profunda", pagina: 102, id: "" },
      { numero: 75, referencia: "João 8.12", tags: "luz / mundo / seguidores", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / a) A luz da Igreja vem de Cristo", pagina: 102, id: "jo8.12" },
      { numero: 76, referencia: "Efésios 5.8", tags: "trevas / luz / fruto", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / a) A luz da Igreja vem de Cristo", pagina: 102, id: "ef5.8" },
      { numero: 77, referencia: "Colossenses 3.17", tags: "tudo em nome de jesus / gratidão", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / b) A luz da Igreja deve brilhar em todos os ambientes da vida", pagina: 103, id: "cl3.17" },
      { numero: 78, referencia: "Efésios 5.11", tags: "trevas / reprovar / luz", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / c) A luz da Igreja não deve se apagar diante das pressões do mundo", pagina: 103, id: "ef5.11" },
      { numero: 79, referencia: "1 Pedro 2.12", tags: "boas obras / gentios / glorificar", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / d) A luz da Igreja pode conduzir outras pessoas a Deus", pagina: 103, id: "1pe2.12" },
      { numero: 80, referencia: "Filipenses 2.15", tags: "luz / mundo / irrepreensível", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / d) A luz da Igreja pode conduzir outras pessoas a Deus", pagina: 103, id: "fp2.15" },
      { numero: 81, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Perguntas Rápidas dentro da Explicação", pagina: 103, id: "" },
      { numero: 82, referencia: "Efésios 5.11", tags: "trevas / reprovar / luz", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Perguntas Rápidas dentro da Explicação / 3. Por que viver como luz pode trazer oposição?", pagina: 103, id: "ef5.11" },
      { numero: 83, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Exemplo Didático", pagina: 104, id: "" },
      { numero: 84, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Exemplo Atual", pagina: 104, id: "" },
      { numero: 85, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Toque de Sabedoria", pagina: 104, id: "" },
      { numero: 86, referencia: "1 Tessalonicenses 5.5", tags: "filhos da luz / dia / vigilância", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Você Sabia?", pagina: 104, id: "1ts5.5" },
      { numero: 87, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / História Ilustrativa – A Casa Iluminada", pagina: 104, id: "" },
      { numero: 88, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Palavra Pastoral", pagina: 105, id: "" },
      { numero: 89, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Aplicação Prática – Marque suas Respostas", pagina: 105, id: "" },
      { numero: 90, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Tarefa Simples para o Coração", pagina: 105, id: "" },
      { numero: 91, referencia: "", tags: "", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Espaço para Resposta", pagina: 105, id: "" }
    ],
  
    listaAlfabetica: [
      { referencia: "1 Co 5.6", tags: "fermento / pecado / contaminação", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / a) A Igreja deve confrontar o pecado com fidelidade bíblica", pagina: 87, id: "1co5.6" },
      { referencia: "1 Co 9.22", tags: "fazer-me tudo / salvar / evangelho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / c) A Igreja deve usar meios culturais para comunicar o evangelho", pagina: 98, id: "1co9.22" },
      { referencia: "1 Pe 1.15-16", tags: "santidade / chamado / imitar", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "1pe1.15-16" },
      { referencia: "1 Pe 1.16", tags: "santidade / imitar deus / chamado", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / a) A Igreja deve confrontar o pecado com fidelidade bíblica", pagina: 87, id: "1pe1.16" },
      { referencia: "1 Pe 2.12", tags: "boas obras / gentios / glorificar", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / d) A luz da Igreja pode conduzir outras pessoas a Deus", pagina: 103, id: "1pe2.12" },
      { referencia: "1 Tm 1.15", tags: "cristo veio / salvar / pecadores", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / a) O silêncio sobre o pecado enfraquece a mensagem do evangelho", pagina: 93, id: "1tm1.15" },
      { referencia: "1 Ts 5.5", tags: "filhos da luz / dia / vigilância", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / Você Sabia?", pagina: 104, id: "1ts5.5" },
      { referencia: "2 Co 2.6-8", tags: "disciplina / perdão / consolação", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Você Sabia?", pagina: 89, id: "2co2.6-8" },
      { referencia: "At 17.6-7", tags: "perturbar / mundo / cristo", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "at17.6-7" },
      { referencia: "At 3.19", tags: "arrependimento / volta / tempos de refrigério", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "at3.19" },
      { referencia: "Cl 3.17", tags: "tudo em nome de jesus / gratidão", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / b) A luz da Igreja deve brilhar em todos os ambientes da vida", pagina: 103, id: "cl3.17" },
      { referencia: "Cl 4.5-6", tags: "sabedoria / tempo / sal", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / b) A Igreja deve dialogar com a cultura sem perder seus princípios", pagina: 98, id: "cl4.5-6" },
      { referencia: "Ef 5.11", tags: "trevas / reprovar / luz", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / c) A luz da Igreja não deve se apagar diante das pressões do mundo", pagina: 103, id: "ef5.11" },
      { referencia: "Ef 5.8", tags: "trevas / luz / fruto", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / a) A luz da Igreja vem de Cristo", pagina: 102, id: "ef5.8" },
      { referencia: "Ez 33.7", tags: "atalaia / alertar / responsabilidade", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Você Sabia?", pagina: 94, id: "ez33.7" },
      { referencia: "Ez 33.7-9", tags: "atalaia / alertar / responsabilidade", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / d) Falar sobre o pecado é um ato de amor", pagina: 93, id: "ez33.7-9" },
      { referencia: "Fp 2.15", tags: "luz / mundo / irrepreensível", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / d) A luz da Igreja pode conduzir outras pessoas a Deus", pagina: 103, id: "fp2.15" },
      { referencia: "Gl 6.1", tags: "restauração / mansidão / pecador", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / Versículo-Chave", pagina: 87, id: "gl6.1" },
      { referencia: "Hb 13.8", tags: "cristo / imutável / ontem e hoje", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / c) A Igreja deve usar meios culturais para comunicar o evangelho", pagina: 98, id: "hb13.8" },
      { referencia: "Is 5.20", tags: "bem / mal / juízo", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / a) A Igreja deve confrontar o pecado com fidelidade bíblica", pagina: 87, id: "is5.20" },
      { referencia: "Jo 15.18-19", tags: "mundo / ódio / escolha", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "jo15.18-19" },
      { referencia: "Jo 1.9", tags: "luz / verdade / ilumina", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / Perguntas Rápidas dentro da Explicação / 4. O que acontece quando o pecado é confessado?", pagina: 94, id: "jo1.9" },
      { referencia: "Jo 8.11", tags: "pecado / perdão / vai e não peques", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / c) A Igreja deve cuidar do pecador com graça", pagina: 88, id: "jo8.11" },
      { referencia: "Jo 8.12", tags: "luz / mundo / seguidores", topico: "📂 Capítulo V / 4. Como a Igreja pode ser luz no mundo? / a) A luz da Igreja vem de Cristo", pagina: 102, id: "jo8.12" },
      { referencia: "Jr 6.14", tags: "paz / ferida / engano", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "jr6.14" },
      { referencia: "Lc 4.18-19", tags: "evangelho / libertação / ano aceitável", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 97, id: "lc4.18-19" },
      { referencia: "Mc 16.15", tags: "ide / evangelho / toda criatura", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Perguntas Rápidas dentro da Explicação / 3. Por que usar meios modernos para evangelizar?", pagina: 99, id: "mc16.15" },
      { referencia: "Mt 5.13-16", tags: "sal / luz / testemunho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / b) A Igreja deve dialogar com a cultura sem perder seus princípios", pagina: 98, id: "mt5.13-16" },
      { referencia: "Mt 5.14-16", tags: "luz / sal / testemunho", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 97, id: "mt5.14-16" },
      { referencia: "Mt 5.16", tags: "boas obras / glorificar / luz", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 98, id: "mt5.16" },
      { referencia: "Mt 7.3-5", tags: "julgamento / hipocrisia / trave e argueiro", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / d) A Igreja deve evitar o espírito de julgamento e hipocrisia", pagina: 88, id: "mt7.3-5" },
      { referencia: "Rm 12.2", tags: "não conformar / renovar / vontade de deus", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / Versículo-Chave", pagina: 97, id: "rm12.2" },
      { referencia: "Rm 3.23", tags: "pecado / glória / todos", topico: "📂 Capítulo V / 2. O que acontece quando a Igreja deixa de falar sobre o pecado? / b) Sem falar sobre pecado, não há arrependimento", pagina: 93, id: "rm3.23" },
      { referencia: "Tg 1.27", tags: "religião pura / órfãos / viúvas", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / a) A Igreja deve influenciar a cultura com valores do Reino", pagina: 97, id: "tg1.27" },
      { referencia: "Tg 4.7", tags: "sujeitar / resistir / diabo", topico: "📂 Capítulo V / 3. A Igreja precisa se adaptar à cultura? / d) O evangelho sempre terá pontos de choque com a cultura", pagina: 98, id: "tg4.7" },
      { referencia: "Tg 5.16", tags: "confissão / oração / cura", topico: "📂 Capítulo V / 1. Como a Igreja deve se posicionar diante do pecado? / b) A Igreja deve orar pela restauração do que caiu", pagina: 88, id: "tg5.16" }
    ]
  };