// ============================================
// DADOS DO CURSO TEOLOGIA DESCOMPLICADA PARA JOVENS
// LIVRO 5 – CAPÍTULO III - POR QUE A UNIÃO DA IGREJA É TÃO IMPORTANTE?
// ============================================

window.dadosLicao = {
  titulo: "📖 CAPÍTULO III - POR QUE A UNIÃO DA IGREJA É TÃO IMPORTANTE?",
  subtitulo: "Teologia Descomplicada para Jovens - Livro 5, Capítulo 3",
  mapaConfig: {
    centro: [31.0461, 34.8516],
    zoom: 6
  },

  listaAparicao: [
    // Abertura
    { numero: 1, referencia: "", tags: "", topico: "📂 Capítulo III", pagina: 44, id: "" },

    // 1. O que significa ser um só corpo em Cristo?
    { numero: 2, referencia: "Romanos 12.5", tags: "corpo de cristo / unidade / membros", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Versículo-Chave", pagina: 45, id: "rm12.5" },
    { numero: 3, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Ideia Central", pagina: 45, id: "" },
    { numero: 4, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Explicação Simples e Profunda", pagina: 45, id: "" },
    { numero: 5, referencia: "Colossenses 1.18", tags: "cabeça da igreja / primazia / cristo", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / a) Cristo é a Cabeça que dirige o corpo", pagina: 45, id: "cl1.18" },
    { numero: 6, referencia: "Efésios 1.22-23", tags: "cabeça / plenitude / igreja", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / a) Cristo é a Cabeça que dirige o corpo", pagina: 45, id: "ef1.22-23" },
    { numero: 7, referencia: "1 Coríntios 12.14-18", tags: "membros / diversidade / função", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / b) Cada membro tem uma função no corpo de Cristo", pagina: 46, id: "1co12.14-18" },
    { numero: 8, referencia: "1 Coríntios 12.21", tags: "interdependência / membros / cuidado", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / c) O corpo de Cristo vive em interdependência", pagina: 46, id: "1co12.21" },
    { numero: 9, referencia: "Atos 2.42", tags: "comunhão / cuidado / ensino", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / d) O corpo precisa de cuidado constante", pagina: 46, id: "at2.42" },
    { numero: 10, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Perguntas Rápidas dentro da Explicação", pagina: 47, id: "" },
    { numero: 11, referencia: "Atos 2.42", tags: "comunhão / saúde espiritual / perseverança", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Perguntas Rápidas dentro da Explicação / 3. O que fortalece a saúde espiritual da Igreja?", pagina: 47, id: "at2.42" },
    { numero: 12, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Exemplo Didático", pagina: 47, id: "" },
    { numero: 13, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Exemplo Atual", pagina: 47, id: "" },
    { numero: 14, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Toque de Sabedoria", pagina: 47, id: "" },
    { numero: 15, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Você Sabia?", pagina: 47, id: "" },
    { numero: 16, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / História Ilustrativa – A Mochila Pesada", pagina: 48, id: "" },
    { numero: 17, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Palavra Pastoral", pagina: 48, id: "" },
    { numero: 18, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Aplicação Prática – Marque suas Respostas", pagina: 48, id: "" },
    { numero: 19, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Tarefa Simples para o Coração", pagina: 49, id: "" },
    { numero: 20, referencia: "", tags: "", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Espaço para Resposta", pagina: 49, id: "" },

    // 2. O que a Ceia do Senhor ensina sobre comunhão?
    { numero: 21, referencia: "1 Coríntios 10.16", tags: "ceia / comunhão / sangue de cristo", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Versículo-Chave", pagina: 50, id: "1co10.16" },
    { numero: 22, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Ideia Central", pagina: 50, id: "" },
    { numero: 23, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Explicação Simples e Profunda", pagina: 50, id: "" },
    { numero: 24, referencia: "Lucas 22.19-20", tags: "ceia / nova aliança / corpo e sangue", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / a) A Ceia fortalece nossa comunhão com Cristo", pagina: 50, id: "lc22.19-20" },
    { numero: 25, referencia: "1 Coríntios 10.16", tags: "comunhão / corpo de cristo / sangue", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / a) A Ceia fortalece nossa comunhão com Cristo", pagina: 50, id: "1co10.16" },
    { numero: 26, referencia: "1 Coríntios 10.16-17", tags: "comunhão / unidade / um só pão", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / b) A Ceia fortalece a comunhão entre os irmãos", pagina: 51, id: "1co10.16-17" },
    { numero: 27, referencia: "Efésios 1.7", tags: "graça / redenção / perdão", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / c) A Ceia lembra nossa dependência da graça", pagina: 51, id: "ef1.7" },
    { numero: 28, referencia: "Efésios 2.8", tags: "graça / salvação / dom de deus", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / c) A Ceia lembra nossa dependência da graça", pagina: 51, id: "ef2.8" },
    { numero: 29, referencia: "1 Coríntios 11.26", tags: "ceia / morte de cristo / segunda vinda", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / d) A Ceia aponta para a volta de Cristo", pagina: 51, id: "1co11.26" },
    { numero: 30, referencia: "Mateus 26.29", tags: "ceia / reino de deus / nova aliança", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / d) A Ceia aponta para a volta de Cristo", pagina: 51, id: "mt26.29" },
    { numero: 31, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Perguntas Rápidas dentro da Explicação", pagina: 52, id: "" },
    { numero: 32, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Exemplo Didático", pagina: 52, id: "" },
    { numero: 33, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Exemplo Atual", pagina: 52, id: "" },
    { numero: 34, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Toque de Sabedoria", pagina: 52, id: "" },
    { numero: 35, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Você Sabia?", pagina: 52, id: "" },
    { numero: 36, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / História Ilustrativa – A Mesa da Comunhão", pagina: 53, id: "" },
    { numero: 37, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Palavra Pastoral", pagina: 53, id: "" },
    { numero: 38, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Aplicação Prática – Marque suas Respostas", pagina: 54, id: "" },
    { numero: 39, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Tarefa Simples para o Coração", pagina: 54, id: "" },
    { numero: 40, referencia: "", tags: "", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Espaço para Resposta", pagina: 54, id: "" },

    // 3. O batismo nos torna parte da Igreja?
    { numero: 41, referencia: "Atos 2.41", tags: "batismo / conversão / entrada na igreja", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Versículo-Chave", pagina: 55, id: "at2.41" },
    { numero: 42, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Ideia Central", pagina: 55, id: "" },
    { numero: 43, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Explicação Simples e Profunda", pagina: 55, id: "" },
    { numero: 44, referencia: "Romanos 6.4", tags: "batismo / morte e ressurreição / nova vida", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / a) O batismo representa identificação com Cristo", pagina: 55, id: "rm6.4" },
    { numero: 45, referencia: "Colossenses 2.12", tags: "batismo / sepultamento / ressurreição", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / a) O batismo representa identificação com Cristo", pagina: 55, id: "cl2.12" },
    { numero: 46, referencia: "Gálatas 3.27", tags: "batismo / revestir de cristo / filhos de deus", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / a) O batismo representa identificação com Cristo", pagina: 55, id: "gl3.27" },
    { numero: 47, referencia: "Atos 2.41", tags: "batismo / comunidade / discipulado", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / b) O batismo marca a entrada na comunidade cristã", pagina: 56, id: "at2.41" },
    { numero: 48, referencia: "Atos 2.42", tags: "comunhão / perseverança / ensino", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / b) O batismo marca a entrada na comunidade cristã", pagina: 56, id: "at2.42" },
    { numero: 49, referencia: "1 Coríntios 12.27", tags: "corpo de cristo / membros / comunhão", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / c) O batismo fortalece a comunhão", pagina: 56, id: "1co12.27" },
    { numero: 50, referencia: "Efésios 4.25", tags: "verdade / membros / comunhão", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / c) O batismo fortalece a comunhão", pagina: 56, id: "ef4.25" },
    { numero: 51, referencia: "2 Coríntios 5.15", tags: "morte de cristo / nova vida / dedicação", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / d) O batismo aponta para uma vida dedicada a Deus", pagina: 56, id: "2co5.15" },
    { numero: 52, referencia: "Colossenses 3.17", tags: "tudo em nome de jesus / gratidão", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / d) O batismo aponta para uma vida dedicada a Deus", pagina: 56, id: "cl3.17" },
    { numero: 53, referencia: "Mateus 5.13-14", tags: "sal da terra / luz do mundo / testemunho", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / d) O batismo aponta para uma vida dedicada a Deus", pagina: 56, id: "mt5.13-14" },
    { numero: 54, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Perguntas Rápidas dentro da Explicação", pagina: 57, id: "" },
    { numero: 55, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Exemplo Didático", pagina: 57, id: "" },
    { numero: 56, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Exemplo Atual", pagina: 57, id: "" },
    { numero: 57, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Toque de Sabedoria", pagina: 57, id: "" },
    { numero: 58, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Você Sabia?", pagina: 58, id: "" },
    { numero: 59, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / História Ilustrativa – O Testemunho Público", pagina: 58, id: "" },
    { numero: 60, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Palavra Pastoral", pagina: 59, id: "" },
    { numero: 61, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Aplicação Prática – Marque suas Respostas", pagina: 59, id: "" },
    { numero: 62, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Tarefa Simples para o Coração", pagina: 59, id: "" },
    { numero: 63, referencia: "", tags: "", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Espaço para Resposta", pagina: 59, id: "" },

    // 4. Como lidar com divisões e desunões na Igreja?
    { numero: 64, referencia: "1 Coríntios 1.10", tags: "divisões / unidade / apelo", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Versículo-Chave", pagina: 60, id: "1co1.10" },
    { numero: 65, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Ideia Central", pagina: 60, id: "" },
    { numero: 66, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Explicação Simples e Profunda", pagina: 60, id: "" },
    { numero: 67, referencia: "Atos 1.14", tags: "oração / unidade / perseverança", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / a) A oração fortalece a unidade da Igreja", pagina: 60, id: "at1.14" },
    { numero: 68, referencia: "Atos 1.14", tags: "oração / unidade / perseverança", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / a) A oração fortalece a unidade da Igreja", pagina: 60, id: "at1.14" },
    { numero: 69, referencia: "Efésios 6.18", tags: "oração / vigilância / intercessão", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / a) A oração fortalece a unidade da Igreja", pagina: 60, id: "ef6.18" },
    { numero: 70, referencia: "Filipenses 2.3-4", tags: "humildade / considerar outros / unidade", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / b) A humildade preserva a unidade", pagina: 61, id: "fp2.3-4" },
    { numero: 71, referencia: "Efésios 4.29", tags: "fofoca / edificação / graça", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / c) Evitar fofocas protege a comunhão", pagina: 61, id: "ef4.29" },
    { numero: 72, referencia: "Colossenses 3.13", tags: "perdão / reconciliação / suportar", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / d) O perdão restaura relacionamentos quebrados", pagina: 61, id: "cl3.13" },
    { numero: 73, referencia: "Romanos 14.19", tags: "paz / edificação / unidade", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / e) A unidade exige esforço de todos", pagina: 61, id: "rm14.19" },
    { numero: 74, referencia: "Efésios 4.3", tags: "unidade / esforço / paz", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / e) A unidade exige esforço de todos", pagina: 61, id: "ef4.3" },
    { numero: 75, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Perguntas Rápidas dentro da Explicação", pagina: 61, id: "" },
    { numero: 76, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Exemplo Didático", pagina: 62, id: "" },
    { numero: 77, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Exemplo Atual", pagina: 62, id: "" },
    { numero: 78, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Toque de Sabedoria", pagina: 62, id: "" },
    { numero: 79, referencia: "1 Coríntios 1.10-13", tags: "divisões / partidarismo / cristo", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Você Sabia?", pagina: 62, id: "1co1.10-13" },
    { numero: 80, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / História Ilustrativa – O Feixe de Gravetos", pagina: 62, id: "" },
    { numero: 81, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Palavra Pastoral", pagina: 63, id: "" },
    { numero: 82, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Aplicação Prática – Marque suas Respostas", pagina: 63, id: "" },
    { numero: 83, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Tarefa Simples para o Coração", pagina: 64, id: "" },
    { numero: 84, referencia: "", tags: "", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Espaço para Resposta", pagina: 64, id: "" }
  ],

  listaAlfabetica: [
    { referencia: "1 Co 1.10", tags: "divisões / unidade / apelo", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Versículo-Chave", pagina: 60, id: "1co1.10" },
    { referencia: "1 Co 1.10-13", tags: "divisões / partidarismo / cristo", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / Você Sabia?", pagina: 62, id: "1co1.10-13" },
    { referencia: "1 Co 10.16", tags: "ceia / comunhão / sangue de cristo", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / Versículo-Chave", pagina: 50, id: "1co10.16" },
    { referencia: "1 Co 10.16-17", tags: "comunhão / unidade / um só pão", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / b) A Ceia fortalece a comunhão entre os irmãos", pagina: 51, id: "1co10.16-17" },
    { referencia: "1 Co 11.26", tags: "ceia / morte de cristo / segunda vinda", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / d) A Ceia aponta para a volta de Cristo", pagina: 51, id: "1co11.26" },
    { referencia: "1 Co 12.14-18", tags: "membros / diversidade / função", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / b) Cada membro tem uma função no corpo de Cristo", pagina: 46, id: "1co12.14-18" },
    { referencia: "1 Co 12.21", tags: "interdependência / membros / cuidado", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / c) O corpo de Cristo vive em interdependência", pagina: 46, id: "1co12.21" },
    { referencia: "1 Co 12.27", tags: "corpo de cristo / membros / comunhão", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / c) O batismo fortalece a comunhão", pagina: 56, id: "1co12.27" },
    { referencia: "2 Co 5.15", tags: "morte de cristo / nova vida / dedicação", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / d) O batismo aponta para uma vida dedicada a Deus", pagina: 56, id: "2co5.15" },
    { referencia: "At 1.14", tags: "oração / unidade / perseverança", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / a) A oração fortalece a unidade da Igreja", pagina: 60, id: "at1.14" },
    { referencia: "At 2.41", tags: "batismo / conversão / entrada na igreja", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / Versículo-Chave", pagina: 55, id: "at2.41" },
    { referencia: "At 2.42", tags: "comunhão / cuidado / ensino", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / d) O corpo precisa de cuidado constante", pagina: 46, id: "at2.42" },
    { referencia: "Cl 1.18", tags: "cabeça da igreja / primazia / cristo", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / a) Cristo é a Cabeça que dirige o corpo", pagina: 45, id: "cl1.18" },
    { referencia: "Cl 2.12", tags: "batismo / sepultamento / ressurreição", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / a) O batismo representa identificação com Cristo", pagina: 55, id: "cl2.12" },
    { referencia: "Cl 3.13", tags: "perdão / reconciliação / suportar", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / d) O perdão restaura relacionamentos quebrados", pagina: 61, id: "cl3.13" },
    { referencia: "Cl 3.17", tags: "tudo em nome de jesus / gratidão", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / d) O batismo aponta para uma vida dedicada a Deus", pagina: 56, id: "cl3.17" },
    { referencia: "Ef 1.22-23", tags: "cabeça / plenitude / igreja", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / a) Cristo é a Cabeça que dirige o corpo", pagina: 45, id: "ef1.22-23" },
    { referencia: "Ef 1.7", tags: "graça / redenção / perdão", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / c) A Ceia lembra nossa dependência da graça", pagina: 51, id: "ef1.7" },
    { referencia: "Ef 2.8", tags: "graça / salvação / dom de deus", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / c) A Ceia lembra nossa dependência da graça", pagina: 51, id: "ef2.8" },
    { referencia: "Ef 4.25", tags: "verdade / membros / comunhão", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / c) O batismo fortalece a comunhão", pagina: 56, id: "ef4.25" },
    { referencia: "Ef 4.29", tags: "fofoca / edificação / graça", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / c) Evitar fofocas protege a comunhão", pagina: 61, id: "ef4.29" },
    { referencia: "Ef 4.3", tags: "unidade / esforço / paz", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / e) A unidade exige esforço de todos", pagina: 61, id: "ef4.3" },
    { referencia: "Ef 6.18", tags: "oração / vigilância / intercessão", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / a) A oração fortalece a unidade da Igreja", pagina: 60, id: "ef6.18" },
    { referencia: "Fp 2.3-4", tags: "humildade / considerar outros / unidade", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / b) A humildade preserva a unidade", pagina: 61, id: "fp2.3-4" },
    { referencia: "Gl 3.27", tags: "batismo / revestir de cristo / filhos de deus", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / a) O batismo representa identificação com Cristo", pagina: 55, id: "gl3.27" },
    { referencia: "Lc 22.19-20", tags: "ceia / nova aliança / corpo e sangue", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / a) A Ceia fortalece nossa comunhão com Cristo", pagina: 50, id: "lc22.19-20" },
    { referencia: "Mt 26.29", tags: "ceia / reino de deus / nova aliança", topico: "📂 Capítulo III / 2. O que a Ceia do Senhor ensina sobre comunhão? / d) A Ceia aponta para a volta de Cristo", pagina: 51, id: "mt26.29" },
    { referencia: "Mt 5.13-14", tags: "sal da terra / luz do mundo / testemunho", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / d) O batismo aponta para uma vida dedicada a Deus", pagina: 56, id: "mt5.13-14" },
    { referencia: "Rm 12.5", tags: "corpo de cristo / unidade / membros", topico: "📂 Capítulo III / 1. O que significa ser um só corpo em Cristo? / Versículo-Chave", pagina: 45, id: "rm12.5" },
    { referencia: "Rm 14.19", tags: "paz / edificação / unidade", topico: "📂 Capítulo III / 4. Como lidar com divisões e desunões na Igreja? / e) A unidade exige esforço de todos", pagina: 61, id: "rm14.19" },
    { referencia: "Rm 6.4", tags: "batismo / morte e ressurreição / nova vida", topico: "📂 Capítulo III / 3. O batismo nos torna parte da Igreja? / a) O batismo representa identificação com Cristo", pagina: 55, id: "rm6.4" }
  ]
};