// ============================================
// LIVRO 5 - CAPÍTULO 1
// O QUE É A IGREJA, AFINAL?
// ============================================

window.dadosLicao = {
  titulo: "📖 CAPÍTULO I - O QUE É A IGREJA, AFINAL?",
  subtitulo: "Livro 5 - Capítulo 1 | Curso Teologia Descomplicada para Jovens",
  
  mapaConfig: {
    centro: [31.5, 35.0],
    zoom: 7,
    marcadores: [
      { lat: 31.7683, lng: 35.2137, local: "Jerusalém", popup: "Jerusalém - Nascimento da Igreja em Pentecostes" },
      { lat: 37.9838, lng: 23.7275, local: "Atenas", popup: "Atenas - Paulo pregando no Areópago" },
      { lat: 37.9397, lng: 22.9338, local: "Corinto", popup: "Corinto - Igreja local mencionada por Paulo" },
      { lat: 38.9637, lng: 35.2433, local: "Galácia", popup: "Galácia - Cartas de Paulo às igrejas" }
    ]
  },
  
  listaAparicao: [
    { numero: 1, referencia: "1 Coríntios 3.16", tags: "templo / Deus / habitação", topico: "📖 Capítulo I / Versículo-Chave", pagina: 3, id: "1co3.16" },
    { numero: 2, referencia: "Mateus 16.18", tags: "pedra / igreja / portas do inferno", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3, id: "mt16.18" },
    { numero: 3, referencia: "1 Coríntios 12.27", tags: "corpo / membros / Cristo", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3, id: "1co12.27" },
    { numero: 4, referencia: "Efésios 2.20", tags: "fundamento / apóstolos / profetas", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3, id: "ef2.20" },
    { numero: 5, referencia: "1 Pedro 2.5", tags: "pedras vivas / sacerdócio / espiritual", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3, id: "1pe2.5" },
    { numero: 6, referencia: "Romanos 12.5", tags: "membros / uns dos outros / corpo", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 4, id: "rm12.5" },
    { numero: 7, referencia: "Hebreus 10.25", tags: "congregação / exortação / dia", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4, id: "hb10.25" },
    { numero: 8, referencia: "Atos 2.42", tags: "doutrina / comunhão / oração", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4, id: "at2.42" },
    { numero: 9, referencia: "1 Tessalonicenses 5.11", tags: "consolar / edificar / próximo", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4, id: "1ts5.11" },
    { numero: 10, referencia: "1 Coríntios 12.7", tags: "dons / proveito / comum", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4, id: "1co12.7" },
    { numero: 11, referencia: "Atos 2.46", tags: "templo / partiam pão / alegria", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / c) O templo é o espaço do culto comunitário", pagina: 4, id: "at2.46" },
    { numero: 12, referencia: "Sem referência", tags: "cristãos isolados / enfraquecimento", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / d) Cristãos isolados se enfraquecem", pagina: 4, id: null },
    { numero: 13, referencia: "Perguntas rápidas", tags: "reflexão / perguntas", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Perguntas rápidas dentro da explicação", pagina: 4, id: null },
    { numero: 14, referencia: "Exemplo Didático", tags: "exemplo / ensino", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Exemplo Didático", pagina: 5, id: null },
    { numero: 15, referencia: "Mateus 28.20", tags: "presença / sempre / Jesus", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Exemplo Atual", pagina: 5, id: "mt28.20" },
    { numero: 16, referencia: "Toque de Sabedoria", tags: "sabedoria / reflexão", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Toque de Sabedoria", pagina: 5, id: null },
    { numero: 17, referencia: "Romanos 16.5", tags: "igreja em casa / Priscila / Áquila", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Você Sabia?", pagina: 5, id: "rm16.5" },
    { numero: 18, referencia: "Atos 2.46", tags: "templo / casa / alegria", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Você Sabia?", pagina: 5, id: "at2.46" },
    { numero: 19, referencia: "Colossenses 1.23", tags: "evangelho / todo mundo / pregado", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Você Sabia?", pagina: 5, id: "cl1.23" },
    { numero: 20, referencia: "História Ilustrativa", tags: "ilustração / prédio", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / História Ilustrativa - Mais que um prédio", pagina: 6, id: null },
    { numero: 21, referencia: "Palavra Pastoral", tags: "pastoral / encorajamento", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Palavra Pastoral", pagina: 6, id: null },
    { numero: 22, referencia: "Aplicação Prática", tags: "questionário / marcar", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Aplicação Prática - Marque suas respostas", pagina: 7, id: null },
    { numero: 23, referencia: "Aplicação Prática", tags: "questionário / marcar", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Aplicação Prática - Marque suas respostas", pagina: 7, id: null },
    { numero: 24, referencia: "Tarefa Simples", tags: "tarefa / coração", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Tarefa Simples para o Coração", pagina: 7, id: null },
    { numero: 25, referencia: "Espaço para Respostas", tags: "respostas / anotações", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Espaço para Respostas", pagina: 7, id: null },
    { numero: 26, referencia: "Atos 2.1", tags: "Pentecostes / cumprido / dia", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Versículo-Chave", pagina: 8, id: "at2.1" },
    { numero: 27, referencia: "Atos 2.1-4", tags: "Pentecostes / Espírito / línguas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Ideia Central", pagina: 8, id: "at2.1-4" },
    { numero: 28, referencia: "Atos 1.4-5", tags: "promessa / batismo / Espírito", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Aplicação Simples e Profunda", pagina: 8, id: "at1.4" },
    { numero: 29, referencia: "Atos 1.14", tags: "oração / unânime / discípulos", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Aplicação Simples e Profunda", pagina: 8, id: "at1.14" },
    { numero: 30, referencia: "Atos 1.3", tags: "quarenta dias / reino / Deus", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 8, id: "at1.3" },
    { numero: 31, referencia: "Levítico 23.15-16", tags: "Pentecostes / festa / semanas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 8, id: "lv23.15" },
    { numero: 32, referencia: "Atos 2.5", tags: "judeus / devotos / nação", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 8, id: "at2.5" },
    { numero: 33, referencia: "Atos 2.1-4", tags: "Pentecostes / vento / fogo", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 9, id: "at2.1-4" },
    { numero: 34, referencia: "Atos 2.4", tags: "cheios / Espírito / falar", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / b) Começou com capacitação do Espírito Santo", pagina: 9, id: "at2.4" },
    { numero: 35, referencia: "Atos 2.6-8", tags: "multidão / línguas / ouvindo", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / b) Começou com capacitação do Espírito Santo", pagina: 9, id: "at2.6" },
    { numero: 36, referencia: "Atos 2.11", tags: "maravilhas / Deus / pregando", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / b) Começou com capacitação do Espírito Santo", pagina: 9, id: "at2.11" },
    { numero: 37, referencia: "Joel 2.28", tags: "derramar / Espírito / profecia", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9, id: "jl2.28" },
    { numero: 38, referencia: "Atos 2.16-17", tags: "Joel / profecia / últimos dias", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9, id: "at2.16" },
    { numero: 39, referencia: "Atos 2.22-23", tags: "Jesus / nazareno / crucificado", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9, id: "at2.22" },
    { numero: 40, referencia: "Atos 2.24", tags: "ressurreição / morte / libertou", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9, id: "at2.24" },
    { numero: 41, referencia: "Atos 2.32-36", tags: "testemunhas / exaltado / Senhor", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9, id: "at2.32" },
    { numero: 42, referencia: "Atos 2.37", tags: "compungidos / coração / perguntaram", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / d) Começou com vidas transformadas pelo Espírito Santo", pagina: 9, id: "at2.37" },
    { numero: 43, referencia: "Atos 2.38", tags: "arrependei / batismo / perdão", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / d) Começou com vidas transformadas pelo Espírito Santo", pagina: 9, id: "at2.38" },
    { numero: 44, referencia: "Atos 2.41", tags: "batizados / três mil / almas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / d) Começou com vidas transformadas pelo Espírito Santo", pagina: 9, id: "at2.41" },
    { numero: 45, referencia: "Perguntas rápidas", tags: "reflexão / perguntas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Perguntas rápidas dentro da explicação", pagina: 10, id: null },
    { numero: 46, referencia: "Atos 2.1", tags: "Pentecostes / cumprido", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Perguntas rápidas dentro da explicação/1.", pagina: 10, id: "at2.1" },
    { numero: 47, referencia: "Atos 2.4", tags: "Espírito / línguas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Perguntas rápidas dentro da explicação/2.", pagina: 10, id: "at2.4" },
    { numero: 48, referencia: "Atos 2.22-24", tags: "Jesus / crucificado / ressurreto", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Perguntas rápidas dentro da explicação/3.", pagina: 10, id: "at2.22" },
    { numero: 49, referencia: "Atos 2.37-41", tags: "arrependimento / batismo / 3000", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Perguntas rápidas dentro da explicação/4.", pagina: 10, id: "at2.37" },
    { numero: 50, referencia: "Atos 2.37-41", tags: "arrependimento / batismo / 3000", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Perguntas rápidas dentro da explicação/4.", pagina: 10, id: "at2.37" },
    { numero: 51, referencia: "Exemplo Didático", tags: "exemplo / ensino", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Exemplo Didático", pagina: 10, id: null },
    { numero: 52, referencia: "Exemplo Atual", tags: "exemplo / atual", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Exemplo Atual", pagina: 10, id: null },
    { numero: 53, referencia: "Toque de Sabedoria", tags: "sabedoria / reflexão", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Toque de Sabedoria", pagina: 10, id: null },
    { numero: 54, referencia: "Atos 2.9-11", tags: "nações / línguas / ouvindo", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Você Sabia?", pagina: 11, id: "at2.9" },
    { numero: 55, referencia: "História Ilustrativa", tags: "vigília / ilustração", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / História Ilustrativa - A vigília Inesquecível", pagina: 11, id: null },
    { numero: 56, referencia: "Palavra Pastoral", tags: "pastoral / encorajamento", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Palavra Pastoral", pagina: 11, id: null },
    { numero: 57, referencia: "Aplicação Prática", tags: "questionário / marcar", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Aplicação Prática - Marque Suas Respostas", pagina: 12, id: null },
    { numero: 58, referencia: "Espaço para Respostas", tags: "respostas / anotações", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Espaço para Respostas", pagina: 12, id: null },
    { numero: 59, referencia: "Tarefa Simples", tags: "tarefa / coração", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Tarefa Simples para o Coração", pagina: 12, id: null },
    { numero: 60, referencia: "1 Coríntios 12.12", tags: "corpo / muitos / membros", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Versículo-Chave", pagina: 13, id: "1co12.12" },
    { numero: 61, referencia: "Ideia Central", tags: "ideia / universal / local", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Ideia Central", pagina: 13, id: null },
    { numero: 62, referencia: "Explicação", tags: "explicação / simples", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Explicação Simples e Profunda", pagina: 13, id: null },
    { numero: 63, referencia: "Apocalipse 7.9", tags: "multidão / nações / tribos", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / a) A Igreja universal", pagina: 13, id: "ap7.9" },
    { numero: 64, referencia: "Efésios 1.22-23", tags: "cabeça / corpo / igreja", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / a) A Igreja universal", pagina: 14, id: "ef1.22" },
    { numero: 65, referencia: "Atos 2.42", tags: "doutrina / comunhão / oração", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / b) A Igreja local", pagina: 14, id: "at2.42" },
    { numero: 66, referencia: "1 Coríntios 1.2", tags: "igreja / Corinto / santificados", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / b) A Igreja local", pagina: 14, id: "1co1.2" },
    { numero: 67, referencia: "1 Coríntios 12.27", tags: "corpo / Cristo / membros", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / c) Ambas são inseparáveis", pagina: 14, id: "1co12.27" },
    { numero: 68, referencia: "Colossenses 1.18", tags: "cabeça / corpo / primícias", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / c) Ambas são inseparáveis", pagina: 14, id: "cl1.18" },
    { numero: 69, referencia: "Romanos 12.5", tags: "membros / uns dos outros", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / c) Ambas são inseparáveis", pagina: 14, id: "rm12.5" },
    { numero: 70, referencia: "Atos 20.28", tags: "pastor / igreja / sangue", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / d) Importância de pertencer a uma igreja local", pagina: 14, id: "at20.28" },
    { numero: 71, referencia: "Hebreus 13.17", tags: "obedecer / líderes / vigiam", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / d) Importância de pertencer a uma igreja local", pagina: 14, id: "hb13.17" },
    { numero: 72, referencia: "Perguntas Rápidas", tags: "perguntas / reflexão", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Perguntas Rápidas dentro da Explicação", pagina: 15, id: null },
    { numero: 73, referencia: "Exemplo Didático", tags: "exemplo / ensino", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Exemplo Didático", pagina: 15, id: null },
    { numero: 74, referencia: "Exemplo Atual", tags: "exemplo / atual", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Exemplo Atual", pagina: 15, id: null },
    { numero: 75, referencia: "Toque de Sabedoria", tags: "sabedoria / reflexão", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Toque de Sabedoria", pagina: 15, id: null },
    { numero: 76, referencia: "Você Sabia?", tags: "curiosidade / igreja", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Você Sabia?", pagina: 15, id: null },
    { numero: 77, referencia: "História Ilustrativa", tags: "tela / ilustração", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / História ilustrativa - Muito além da Tela", pagina: 16, id: null },
    { numero: 78, referencia: "Palavra Pastoral", tags: "pastoral / encorajamento", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Palavra Pastoral", pagina: 16, id: null },
    { numero: 79, referencia: "Aplicação Prática", tags: "questionário / marcar", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Aplicação Prática - Marque suas Respostas", pagina: 17, id: null },
    { numero: 80, referencia: "Tarefa Simples", tags: "tarefa / coração", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Tarefa Simples para o Coração", pagina: 17, id: null },
    { numero: 81, referencia: "Espaço para Resposta", tags: "resposta / anotação", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Espaço para Resposta", pagina: 17, id: null },
    { numero: 82, referencia: "Efésios 5.25", tags: "amar / igreja / entregou", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Versículo-Chave", pagina: 18, id: "ef5.25" },
    { numero: 83, referencia: "Ideia Central", tags: "ideia / amor / igreja", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Ideia Central", pagina: 18, id: null },
    { numero: 84, referencia: "Explicação", tags: "explicação / simples", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Explicação Simples e Profunda", pagina: 18, id: null },
    { numero: 85, referencia: "Colossenses 1.18", tags: "cabeça / corpo / primícias", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / a) A Igreja é o corpo de Cristo", pagina: 18, id: "cl1.18" },
    { numero: 86, referencia: "Atos 9.4", tags: "Saulo / perseguir / Jesus", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / a) A Igreja é o corpo de Cristo", pagina: 18, id: "at9.4" },
    { numero: 87, referencia: "Efésios 1.22-23", tags: "cabeça / corpo / plenitude", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / a) A Igreja é o corpo de Cristo", pagina: 18, id: "ef1.22" },
    { numero: 88, referencia: "Apocalipse 19.7-8", tags: "bodas / Cordeiro / noiva", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / b) A Igreja é a noiva de Cristo", pagina: 18, id: "ap19.7" },
    { numero: 89, referencia: "Efésios 5.27", tags: "igreja / gloriosa / sem mancha", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / b) A Igreja é a noiva de Cristo", pagina: 19, id: "ef5.27" },
    { numero: 90, referencia: "Efésios 5.25", tags: "amar / igreja / entregou", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / c) Jesus deu a vida pela Igreja", pagina: 19, id: "ef5.25" },
    { numero: 91, referencia: "Atos 20.28", tags: "pastor / igreja / sangue", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / c) Jesus deu a vida pela Igreja", pagina: 19, id: "at20.28" },
    { numero: 92, referencia: "Efésios 2.19", tags: "estrangeiros / concidadãos / família", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / d) Porque a Igreja é a família de Deus", pagina: 19, id: "ef2.19" },
    { numero: 93, referencia: "Gálatas 6.10", tags: "fazer bem / família / fé", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / d) Porque a Igreja é a família de Deus", pagina: 19, id: "gl6.10" },
    { numero: 94, referencia: "Perguntas Rápidas", tags: "perguntas / reflexão", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Perguntas Rápidas dentro da Explicação", pagina: 19, id: null },
    { numero: 95, referencia: "Apocalipse 21.2", tags: "nova Jerusalém / noiva", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Exemplo Didático", pagina: 20, id: "ap21.2" },
    { numero: 96, referencia: "Apocalipse 21.2", tags: "nova Jerusalém / noiva", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Exemplo Atual", pagina: 20, id: "ap21.2" },
    { numero: 97, referencia: "Apocalipse 21.2", tags: "nova Jerusalém / noiva", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Toque de Sabedoria", pagina: 20, id: "ap21.2" },
    { numero: 98, referencia: "Oséias 2.19-20", tags: "desposar / justiça / amor", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Você Sabia?", pagina: 20, id: "os2.19" },
    { numero: 99, referencia: "História Ilustrativa", tags: "noiva / ilustração", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / História Ilustrativa - A Noiva Amada de Cristo", pagina: 21, id: null },
    { numero: 100, referencia: "Palavra Pastoral", tags: "pastoral / encorajamento", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Palavra Pastoral", pagina: 21, id: null },
    { numero: 101, referencia: "Aplicação Prática", tags: "questionário / marcar", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Aplicação Prática - Marque suas Respostas", pagina: 22, id: null },
    { numero: 102, referencia: "Tarefa Simples", tags: "tarefa / coração", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Tarefa Simples para o Coração", pagina: 22, id: null },
    { numero: 103, referencia: "Espaço para Resposta", tags: "resposta / anotação", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Espaço para Resposta", pagina: 22, id: null }
  ],
  
  listaAlfabetica: [
    { id: "1co1.2", referencia: "1 Coríntios 1.2", tags: "igreja / Corinto / santificados", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / b) A Igreja local", pagina: 14 },
    { id: "1co12.12", referencia: "1 Coríntios 12.12", tags: "corpo / muitos / membros", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / Versículo-Chave", pagina: 13 },
    { id: "1co12.27", referencia: "1 Coríntios 12.27", tags: "corpo / membros / Cristo", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3 },
    { id: "1co12.7", referencia: "1 Coríntios 12.7", tags: "dons / proveito / comum", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4 },
    { id: "1co3.16", referencia: "1 Coríntios 3.16", tags: "templo / Deus / habitação", topico: "📖 Capítulo I / Versículo-Chave", pagina: 3 },
    { id: "1pe2.5", referencia: "1 Pedro 2.5", tags: "pedras vivas / sacerdócio / espiritual", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3 },
    { id: "1ts5.11", referencia: "1 Tessalonicenses 5.11", tags: "consolar / edificar / próximo", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4 },
    { id: "ap19.7", referencia: "Apocalipse 19.7-8", tags: "bodas / Cordeiro / noiva", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / b) A Igreja é a noiva de Cristo", pagina: 18 },
    { id: "ap21.2", referencia: "Apocalipse 21.2", tags: "nova Jerusalém / noiva", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Exemplo Didático", pagina: 20 },
    { id: "ap7.9", referencia: "Apocalipse 7.9", tags: "multidão / nações / tribos", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / a) A Igreja universal", pagina: 13 },
    { id: "at1.14", referencia: "Atos 1.14", tags: "oração / unânime / discípulos", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Aplicação Simples e Profunda", pagina: 8 },
    { id: "at1.3", referencia: "Atos 1.3", tags: "quarenta dias / reino / Deus", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 8 },
    { id: "at1.4", referencia: "Atos 1.4-5", tags: "promessa / batismo / Espírito", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Aplicação Simples e Profunda", pagina: 8 },
    { id: "at2.1", referencia: "Atos 2.1", tags: "Pentecostes / cumprido / dia", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Versículo-Chave", pagina: 8 },
    { id: "at2.11", referencia: "Atos 2.11", tags: "maravilhas / Deus / pregando", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / b) Começou com capacitação do Espírito Santo", pagina: 9 },
    { id: "at2.16", referencia: "Atos 2.16-17", tags: "Joel / profecia / últimos dias", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9 },
    { id: "at2.22", referencia: "Atos 2.22-23", tags: "Jesus / nazareno / crucificado", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9 },
    { id: "at2.24", referencia: "Atos 2.24", tags: "ressurreição / morte / libertou", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9 },
    { id: "at2.32", referencia: "Atos 2.32-36", tags: "testemunhas / exaltado / Senhor", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9 },
    { id: "at2.37", referencia: "Atos 2.37", tags: "compungidos / coração / perguntaram", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / d) Começou com vidas transformadas pelo Espírito Santo", pagina: 9 },
    { id: "at2.38", referencia: "Atos 2.38", tags: "arrependei / batismo / perdão", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / d) Começou com vidas transformadas pelo Espírito Santo", pagina: 9 },
    { id: "at2.41", referencia: "Atos 2.41", tags: "batizados / três mil / almas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / d) Começou com vidas transformadas pelo Espírito Santo", pagina: 9 },
    { id: "at2.42", referencia: "Atos 2.42", tags: "doutrina / comunhão / oração", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4 },
    { id: "at2.46", referencia: "Atos 2.46", tags: "templo / partiam pão / alegria", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / c) O templo é o espaço do culto comunitário", pagina: 4 },
    { id: "at2.5", referencia: "Atos 2.5", tags: "judeus / devotos / nação", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 8 },
    { id: "at2.6", referencia: "Atos 2.6-8", tags: "multidão / línguas / ouvindo", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / b) Começou com capacitação do Espírito Santo", pagina: 9 },
    { id: "at2.9", referencia: "Atos 2.9-11", tags: "nações / línguas / ouvindo", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / Você Sabia?", pagina: 11 },
    { id: "at20.28", referencia: "Atos 20.28", tags: "pastor / igreja / sangue", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / d) Importância de pertencer a uma igreja local", pagina: 14 },
    { id: "at9.4", referencia: "Atos 9.4", tags: "Saulo / perseguir / Jesus", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / a) A Igreja é o corpo de Cristo", pagina: 18 },
    { id: "cl1.18", referencia: "Colossenses 1.18", tags: "cabeça / corpo / primícias", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / c) Ambas são inseparáveis", pagina: 14 },
    { id: "cl1.23", referencia: "Colossenses 1.23", tags: "evangelho / todo mundo / pregado", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Você Sabia?", pagina: 5 },
    { id: "ef1.22", referencia: "Efésios 1.22-23", tags: "cabeça / corpo / igreja", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / a) A Igreja universal", pagina: 14 },
    { id: "ef2.19", referencia: "Efésios 2.19", tags: "estrangeiros / concidadãos / família", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / d) Porque a Igreja é a família de Deus", pagina: 19 },
    { id: "ef2.20", referencia: "Efésios 2.20", tags: "fundamento / apóstolos / profetas", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3 },
    { id: "ef5.25", referencia: "Efésios 5.25", tags: "amar / igreja / entregou", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Versículo-Chave", pagina: 18 },
    { id: "ef5.27", referencia: "Efésios 5.27", tags: "igreja / gloriosa / sem mancha", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / b) A Igreja é a noiva de Cristo", pagina: 19 },
    { id: "gl6.10", referencia: "Gálatas 6.10", tags: "fazer bem / família / fé", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / d) Porque a Igreja é a família de Deus", pagina: 19 },
    { id: "hb10.25", referencia: "Hebreus 10.25", tags: "congregação / exortação / dia", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / b) O culto público é prática bíblica", pagina: 4 },
    { id: "hb13.17", referencia: "Hebreus 13.17", tags: "obedecer / líderes / vigiam", topico: "📖 Capítulo I / 3. A Igreja é universal ou local? / d) Importância de pertencer a uma igreja local", pagina: 14 },
    { id: "jl2.28", referencia: "Joel 2.28", tags: "derramar / Espírito / profecia", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / c) Começou com a pregação do evangelho", pagina: 9 },
    { id: "lv23.15", referencia: "Levítico 23.15-16", tags: "Pentecostes / festa / semanas", topico: "📖 Capítulo I / 2. Como a Igreja começou no Novo Testamento? / a) Começou no dia de Pentecostes", pagina: 8 },
    { id: "mt16.18", referencia: "Mateus 16.18", tags: "pedra / igreja / portas do inferno", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 3 },
    { id: "mt28.20", referencia: "Mateus 28.20", tags: "presença / sempre / Jesus", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Exemplo Atual", pagina: 5 },
    { id: "os2.19", referencia: "Oséias 2.19-20", tags: "desposar / justiça / amor", topico: "📖 Capítulo I / 4. Por que Jesus ama tanto a Igreja? / Você Sabia?", pagina: 20 },
    { id: "rm12.5", referencia: "Romanos 12.5", tags: "membros / uns dos outros / corpo", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / a) A Igreja é mais que paredes", pagina: 4 },
    { id: "rm16.5", referencia: "Romanos 16.5", tags: "igreja em casa / Priscila / Áquila", topico: "📖 Capítulo I / 1. A Igreja é um prédio ou um povo? / Você Sabia?", pagina: 5 }
  ]
};

console.log("✅ dados-lv5-cp1.js carregado com sucesso!");
console.log(`📊 Total de versículos: ${window.dadosLicao.listaAparicao.length}`);