// ============================================
// DADOS DO CURSO TEOLOGIA DESCOMPLICADA PARA JOVENS
// LIVRO 5 – CAPÍTULO VI - DÚVIDAS SINCERAS QUE OS JOVENS TÊM
// ============================================

window.dadosLicao = {
    titulo: "📖 CAPÍTULO VI - DÚVIDAS SINCERAS QUE OS JOVENS TÊM",
    subtitulo: "Teologia Descomplicada para Jovens - Livro 5, Capítulo 6",
    mapaConfig: {
      centro: [31.0461, 34.8516],
      zoom: 6
    },
  
    listaAparicao: [
      // Abertura
      { numero: 1, referencia: "", tags: "", topico: "📂 Capítulo VI", pagina: 107, id: "" },
  
      // 1. Se já sou salvo, por que devo frequentar o templo?
      { numero: 2, referencia: "Hebreus 10.25", tags: "congregação / comunhão / exortação", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Versículo-Chave", pagina: 108, id: "hb10.25" },
      { numero: 3, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Ideia Central", pagina: 108, id: "" },
      { numero: 4, referencia: "Efésios 2.8-9", tags: "graça / salvação / dom de deus", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Explicação Simples e Profunda", pagina: 108, id: "ef2.8-9" },
      { numero: 5, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / a) A reunião no templo protege contra o isolamento espiritual", pagina: 108, id: "" },
      { numero: 6, referencia: "Atos 2.42", tags: "comunhão / ensino / perseverança", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / b) No templo aprendemos disciplina espiritual", pagina: 109, id: "at2.42" },
      { numero: 7, referencia: "Mateus 6.6,16", tags: "oração / jejum / disciplina", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / b) No templo aprendemos disciplina espiritual", pagina: 109, id: "mt6.6-16" },
      { numero: 8, referencia: "Colossenses 3.16", tags: "palavra / ensino / admoestação", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / b) No templo aprendemos disciplina espiritual", pagina: 109, id: "cl3.16" },
      { numero: 9, referencia: "1 Tessalonicenses 5.11", tags: "consolar / edificar / exortação", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / c) No templo somos encorajados pelos testemunhos dos irmãos", pagina: 109, id: "1ts5.11" },
      { numero: 10, referencia: "Mateus 28.19-20", tags: "grande comissão / discipulado / missão", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / d) No templo somos preparados para cumprir a missão de Deus", pagina: 109, id: "mt28.19-20" },
      { numero: 11, referencia: "Filipenses 4.15-16", tags: "comunhão / oferta / necessidade", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / d) No templo somos preparados para cumprir a missão de Deus", pagina: 109, id: "fp4.15-16" },
      { numero: 12, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação", pagina: 109, id: "" },
      { numero: 13, referencia: "Hebreus 10.24-25", tags: "congregação / exortação / amor", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação / 1. Por que a reunião no templo é importante para o cristão?", pagina: 109, id: "hb10.24-25" },
      { numero: 14, referencia: "Mateus 6.6,16", tags: "oração / jejum / disciplina", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação / 2. O que aprendemos no templo além da Palavra?", pagina: 109, id: "mt6.6-16" },
      { numero: 15, referencia: "Apocalipse 12.11", tags: "testemunho / sangue / vitória", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação / 3. Como os testemunhos dos irmãos ajudam a Igreja?", pagina: 109, id: "ap12.11" },
      { numero: 16, referencia: "Mateus 28.19-20", tags: "grande comissão / discipulado / missão", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação / 4. Para que a Igreja prepara os cristãos?", pagina: 110, id: "mt28.19-20" },
      { numero: 17, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Exemplo Didático", pagina: 110, id: "" },
      { numero: 18, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Exemplo Atual", pagina: 110, id: "" },
      { numero: 19, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Toque de Sabedoria", pagina: 110, id: "" },
      { numero: 20, referencia: "Efésios 2.19", tags: "concidadãos / família / povo de deus", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Você Sabia?", pagina: 110, id: "ef2.19" },
      { numero: 21, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / História Ilustrativa – O Carvão que se Esfriou", pagina: 110, id: "" },
      { numero: 22, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Palavra Pastoral", pagina: 111, id: "" },
      { numero: 23, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Aplicação Prática – Marque suas Respostas", pagina: 112, id: "" },
      { numero: 24, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Tarefa Simples para o Coração", pagina: 112, id: "" },
      { numero: 25, referencia: "", tags: "", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Espaço para Resposta", pagina: 112, id: "" },
  
      // 2. O que fazer quando a Igreja falha comigo?
      { numero: 26, referencia: "Colossenses 3.13", tags: "perdão / reconciliação / suportar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Versículo-Chave", pagina: 113, id: "cl3.13" },
      { numero: 27, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Ideia Central", pagina: 113, id: "" },
      { numero: 28, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Explicação Simples e Profunda", pagina: 113, id: "" },
      { numero: 29, referencia: "Filipenses 1.6", tags: "confiança / obra / completar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / a) Lembre-se de que a Igreja é formada por pessoas imperfeitas", pagina: 114, id: "fp1.6" },
      { numero: 30, referencia: "1 João 1.8", tags: "pecado / engano / verdade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / a) Lembre-se de que a Igreja é formada por pessoas imperfeitas", pagina: 114, id: "1jo1.8" },
      { numero: 31, referencia: "Colossenses 3.13", tags: "perdão / reconciliação / suportar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / b) Pratique o perdão como Cristo ensinou", pagina: 114, id: "cl3.13" },
      { numero: 32, referencia: "Efésios 4.31-32", tags: "perdão / amargura / bondade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / b) Pratique o perdão como Cristo ensinou", pagina: 114, id: "ef4.31-32" },
      { numero: 33, referencia: "Hebreus 12.2", tags: "foco / jesus / corrida", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / c) Não permita que a decepção destrua sua fé", pagina: 114, id: "hb12.2" },
      { numero: 34, referencia: "Provérbios 11.14", tags: "conselho / orientação / sabedoria", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / d) Busque aconselhamento espiritual saudável", pagina: 114, id: "pv11.14" },
      { numero: 35, referencia: "Hebreus 13.17", tags: "obedecer / autoridades / vigiar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / d) Busque aconselhamento espiritual saudável", pagina: 114, id: "hb13.17" },
      { numero: 36, referencia: "Tiago 1.2-4", tags: "provações / paciência / maturidade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / e) Aprenda a crescer mesmo nas decepções", pagina: 114, id: "tg1.2-4" },
      { numero: 37, referencia: "Romanos 5.3-4", tags: "tribulação / paciência / esperança", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / e) Aprenda a crescer mesmo nas decepções", pagina: 114, id: "rm5.3-4" },
      { numero: 38, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Perguntas Rápidas dentro da Explicação", pagina: 114, id: "" },
      { numero: 39, referencia: "Tiago 1.2-4", tags: "provações / paciência / maturidade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Perguntas Rápidas dentro da Explicação / 4. O que Deus pode produzir através das dificuldades?", pagina: 115, id: "tg1.2-4" },
      { numero: 40, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Exemplo Didático", pagina: 115, id: "" },
      { numero: 41, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Exemplo Atual", pagina: 115, id: "" },
      { numero: 42, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Toque de Sabedoria", pagina: 115, id: "" },
      { numero: 43, referencia: "Atos 15", tags: "conciliação / igreja / conflito", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Você Sabia?", pagina: 115, id: "at15" },
      { numero: 44, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / História Ilustrativa – A Lição do Hospital", pagina: 116, id: "" },
      { numero: 45, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Palavra Pastoral", pagina: 116, id: "" },
      { numero: 46, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Aplicação Prática – Marque suas Respostas", pagina: 117, id: "" },
      { numero: 47, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Tarefa Simples para o Coração", pagina: 117, id: "" },
      { numero: 48, referencia: "", tags: "", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Espaço para Resposta", pagina: 117, id: "" },
  
      // 3. Por que existem tantas denominações diferentes?
      { numero: 49, referencia: "João 17.21", tags: "unidade / oração / cristo", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Versículo-Chave", pagina: 118, id: "jo17.21" },
      { numero: 50, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Ideia Central", pagina: 118, id: "" },
      { numero: 51, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Explicação Simples e Profunda", pagina: 118, id: "" },
      { numero: 52, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / a) Algumas denominações surgiram por diferenças de interpretação bíblica", pagina: 119, id: "" },
      { numero: 53, referencia: "1 Coríntios 1.10-12", tags: "divisões / partidarismo / cristo", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / b) Algumas denominações surgiram por conflitos humanos", pagina: 119, id: "1co1.10-12" },
      { numero: 54, referencia: "Atos 17.26-27", tags: "nações / propósito / buscar deus", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / c) Algumas denominações surgiram por questões históricas e culturais", pagina: 119, id: "at17.26-27" },
      { numero: 55, referencia: "1 Coríntios 12.4-6", tags: "dons / ministérios / diversidade", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / c) Algumas denominações surgiram por questões históricas e culturais", pagina: 119, id: "1co12.4-6" },
      { numero: 56, referencia: "2 Timóteo 3.16-17", tags: "inspiração / ensino / correção", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / d) Algumas denominações surgiram por motivo de reforma e renovação espiritual", pagina: 120, id: "2tm3.16-17" },
      { numero: 57, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Perguntas Rápidas dentro da Explicação", pagina: 120, id: "" },
      { numero: 58, referencia: "2 Timóteo 3.16-17", tags: "inspiração / ensino / correção", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Perguntas Rápidas dentro da Explicação / 3. Por que alguns movimentos de reforma surgiram?", pagina: 120, id: "2tm3.16-17" },
      { numero: 59, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Exemplo Didático", pagina: 120, id: "" },
      { numero: 60, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Exemplo Atual", pagina: 120, id: "" },
      { numero: 61, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Toque de Sabedoria", pagina: 121, id: "" },
      { numero: 62, referencia: "Atos 11.22", tags: "igreja / jerusalém / barnabé", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Você Sabia?", pagina: 121, id: "at11.22" },
      { numero: 63, referencia: "1 Coríntios 1.2", tags: "igreja / santos / invocar", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Você Sabia?", pagina: 121, id: "1co1.2" },
      { numero: 64, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / História Ilustrativa – O Jardim com Muitas Flores", pagina: 121, id: "" },
      { numero: 65, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Palavra Pastoral", pagina: 122, id: "" },
      { numero: 66, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Aplicação Prática – Marque suas Respostas", pagina: 122, id: "" },
      { numero: 67, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Tarefa Simples para o Coração", pagina: 122, id: "" },
      { numero: 68, referencia: "", tags: "", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Espaço para Resposta", pagina: 122, id: "" },
  
      // 4. Qual é o lugar dos jovens na Igreja hoje?
      { numero: 69, referencia: "1 Timóteo 4.12", tags: "jovem / exemplo / fé", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Versículo-Chave", pagina: 123, id: "1tm4.12" },
      { numero: 70, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Ideia Central", pagina: 123, id: "" },
      { numero: 71, referencia: "1 Timóteo 4.12", tags: "jovem / exemplo / fé", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Explicação Simples e Profunda", pagina: 123, id: "1tm4.12" },
      { numero: 72, referencia: "Jeremias 1.6-7", tags: "jovem / chamado / missão", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / a) Deus sempre usou jovens em sua obra", pagina: 123, id: "jr1.6-7" },
      { numero: 73, referencia: "Daniel 1.8", tags: "jovem / decisão / pureza", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / a) Deus sempre usou jovens em sua obra", pagina: 124, id: "dn1.8" },
      { numero: 74, referencia: "2 Crônicas 34.3", tags: "jovem / rei / buscar deus", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / a) Deus sempre usou jovens em sua obra", pagina: 124, id: "2cr34.3" },
      { numero: 75, referencia: "Eclesiastes 12.1", tags: "juventude / lembrar / criador", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / b) Os jovens têm energia e disposição para servir", pagina: 124, id: "ec12.1" },
      { numero: 76, referencia: "Salmos 110.3", tags: "juventude / santidade / exército", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / b) Os jovens têm energia e disposição para servir", pagina: 124, id: "sl110.3" },
      { numero: 77, referencia: "Mateus 5.14-16", tags: "luz / sal / testemunho", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / c) Os jovens podem influenciar sua geração para Cristo", pagina: 124, id: "mt5.14-16" },
      { numero: 78, referencia: "Filipenses 2.15", tags: "luz / mundo / irrepreensível", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / c) Os jovens podem influenciar sua geração para Cristo", pagina: 124, id: "fp2.15" },
      { numero: 79, referencia: "Atos 1.8", tags: "testemunhas / poder / Espírito Santo", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / d) Os jovens participam da continuidade da missão da Igreja", pagina: 124, id: "at1.8" },
      { numero: 80, referencia: "Salmos 145.4", tags: "geração / obras / louvor", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / d) Os jovens participam da continuidade da missão da Igreja", pagina: 124, id: "sl145.4" },
      { numero: 81, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Perguntas Rápidas dentro da Explicação", pagina: 124, id: "" },
      { numero: 82, referencia: "Daniel 1.8", tags: "jovem / decisão / pureza", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Perguntas Rápidas dentro da Explicação / 1. Que decisão Daniel tomou ainda jovem?", pagina: 124, id: "dn1.8" },
      { numero: 83, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Exemplo Didático", pagina: 125, id: "" },
      { numero: 84, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Exemplo Atual", pagina: 125, id: "" },
      { numero: 85, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Toque de Sabedoria", pagina: 125, id: "" },
      { numero: 86, referencia: "1 Timóteo 1.3", tags: "jovem / timóteo / ministério", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Você Sabia?", pagina: 125, id: "1tm1.3" },
      { numero: 87, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / História Ilustrativa – Uma Pequena Luz no Escuro", pagina: 125, id: "" },
      { numero: 88, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Palavra Pastoral", pagina: 127, id: "" },
      { numero: 89, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Aplicação Prática – Marque suas Respostas", pagina: 127, id: "" },
      { numero: 90, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Tarefa Simples para o Coração", pagina: 127, id: "" },
      { numero: 91, referencia: "", tags: "", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Espaço para Resposta", pagina: 127, id: "" }
    ],
  
    listaAlfabetica: [
      { referencia: "1 Co 1.10-12", tags: "divisões / partidarismo / cristo", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / b) Algumas denominações surgiram por conflitos humanos", pagina: 119, id: "1co1.10-12" },
      { referencia: "1 Co 1.2", tags: "igreja / santos / invocar", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Você Sabia?", pagina: 121, id: "1co1.2" },
      { referencia: "1 Co 12.4-6", tags: "dons / ministérios / diversidade", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / c) Algumas denominações surgiram por questões históricas e culturais", pagina: 119, id: "1co12.4-6" },
      { referencia: "1 Jo 1.8", tags: "pecado / engano / verdade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / a) Lembre-se de que a Igreja é formada por pessoas imperfeitas", pagina: 114, id: "1jo1.8" },
      { referencia: "1 Tm 1.3", tags: "jovem / timóteo / ministério", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Você Sabia?", pagina: 125, id: "1tm1.3" },
      { referencia: "1 Tm 4.12", tags: "jovem / exemplo / fé", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / Versículo-Chave", pagina: 123, id: "1tm4.12" },
      { referencia: "1 Ts 5.11", tags: "consolar / edificar / exortação", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / c) No templo somos encorajados pelos testemunhos dos irmãos", pagina: 109, id: "1ts5.11" },
      { referencia: "2 Cr 34.3", tags: "jovem / rei / buscar deus", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / a) Deus sempre usou jovens em sua obra", pagina: 124, id: "2cr34.3" },
      { referencia: "2 Tm 3.16-17", tags: "inspiração / ensino / correção", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / d) Algumas denominações surgiram por motivo de reforma e renovação espiritual", pagina: 120, id: "2tm3.16-17" },
      { referencia: "Ap 12.11", tags: "testemunho / sangue / vitória", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação / 3. Como os testemunhos dos irmãos ajudam a Igreja?", pagina: 109, id: "ap12.11" },
      { referencia: "At 1.8", tags: "testemunhas / poder / Espírito Santo", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / d) Os jovens participam da continuidade da missão da Igreja", pagina: 124, id: "at1.8" },
      { referencia: "At 11.22", tags: "igreja / jerusalém / barnabé", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Você Sabia?", pagina: 121, id: "at11.22" },
      { referencia: "At 15", tags: "conciliação / igreja / conflito", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Você Sabia?", pagina: 115, id: "at15" },
      { referencia: "At 17.26-27", tags: "nações / propósito / buscar deus", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / c) Algumas denominações surgiram por questões históricas e culturais", pagina: 119, id: "at17.26-27" },
      { referencia: "At 2.42", tags: "comunhão / ensino / perseverança", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / b) No templo aprendemos disciplina espiritual", pagina: 109, id: "at2.42" },
      { referencia: "Cl 3.13", tags: "perdão / reconciliação / suportar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / Versículo-Chave", pagina: 113, id: "cl3.13" },
      { referencia: "Cl 3.16", tags: "palavra / ensino / admoestação", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / b) No templo aprendemos disciplina espiritual", pagina: 109, id: "cl3.16" },
      { referencia: "Dn 1.8", tags: "jovem / decisão / pureza", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / a) Deus sempre usou jovens em sua obra", pagina: 124, id: "dn1.8" },
      { referencia: "Ec 12.1", tags: "juventude / lembrar / criador", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / b) Os jovens têm energia e disposição para servir", pagina: 124, id: "ec12.1" },
      { referencia: "Ef 2.19", tags: "concidadãos / família / povo de deus", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Você Sabia?", pagina: 110, id: "ef2.19" },
      { referencia: "Ef 2.8-9", tags: "graça / salvação / dom de deus", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Explicação Simples e Profunda", pagina: 108, id: "ef2.8-9" },
      { referencia: "Ef 4.31-32", tags: "perdão / amargura / bondade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / b) Pratique o perdão como Cristo ensinou", pagina: 114, id: "ef4.31-32" },
      { referencia: "Fp 1.6", tags: "confiança / obra / completar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / a) Lembre-se de que a Igreja é formada por pessoas imperfeitas", pagina: 114, id: "fp1.6" },
      { referencia: "Fp 2.15", tags: "luz / mundo / irrepreensível", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / c) Os jovens podem influenciar sua geração para Cristo", pagina: 124, id: "fp2.15" },
      { referencia: "Fp 4.15-16", tags: "comunhão / oferta / necessidade", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / d) No templo somos preparados para cumprir a missão de Deus", pagina: 109, id: "fp4.15-16" },
      { referencia: "Hb 10.24-25", tags: "congregação / exortação / amor", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Perguntas Rápidas dentro da Explicação / 1. Por que a reunião no templo é importante para o cristão?", pagina: 109, id: "hb10.24-25" },
      { referencia: "Hb 10.25", tags: "congregação / comunhão / exortação", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / Versículo-Chave", pagina: 108, id: "hb10.25" },
      { referencia: "Hb 12.2", tags: "foco / jesus / corrida", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / c) Não permita que a decepção destrua sua fé", pagina: 114, id: "hb12.2" },
      { referencia: "Hb 13.17", tags: "obedecer / autoridades / vigiar", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / d) Busque aconselhamento espiritual saudável", pagina: 114, id: "hb13.17" },
      { referencia: "Jo 17.21", tags: "unidade / oração / cristo", topico: "📂 Capítulo VI / 3. Por que existem tantas denominações diferentes? / Versículo-Chave", pagina: 118, id: "jo17.21" },
      { referencia: "Jr 1.6-7", tags: "jovem / chamado / missão", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / a) Deus sempre usou jovens em sua obra", pagina: 123, id: "jr1.6-7" },
      { referencia: "Mt 28.19-20", tags: "grande comissão / discipulado / missão", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / d) No templo somos preparados para cumprir a missão de Deus", pagina: 109, id: "mt28.19-20" },
      { referencia: "Mt 5.14-16", tags: "luz / sal / testemunho", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / c) Os jovens podem influenciar sua geração para Cristo", pagina: 124, id: "mt5.14-16" },
      { referencia: "Mt 6.6,16", tags: "oração / jejum / disciplina", topico: "📂 Capítulo VI / 1. Se já sou salvo, por que devo frequentar o templo? / b) No templo aprendemos disciplina espiritual", pagina: 109, id: "mt6.6-16" },
      { referencia: "Pv 11.14", tags: "conselho / orientação / sabedoria", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / d) Busque aconselhamento espiritual saudável", pagina: 114, id: "pv11.14" },
      { referencia: "Rm 5.3-4", tags: "tribulação / paciência / esperança", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / e) Aprenda a crescer mesmo nas decepções", pagina: 114, id: "rm5.3-4" },
      { referencia: "Sl 110.3", tags: "juventude / santidade / exército", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / b) Os jovens têm energia e disposição para servir", pagina: 124, id: "sl110.3" },
      { referencia: "Sl 145.4", tags: "geração / obras / louvor", topico: "📂 Capítulo VI / 4. Qual é o lugar dos jovens na Igreja hoje? / d) Os jovens participam da continuidade da missão da Igreja", pagina: 124, id: "sl145.4" },
      { referencia: "Tg 1.2-4", tags: "provações / paciência / maturidade", topico: "📂 Capítulo VI / 2. O que fazer quando a Igreja falha comigo? / e) Aprenda a crescer mesmo nas decepções", pagina: 114, id: "tg1.2-4" }
    ]
  };