// ============================================
// DADOS DO CURSO TEOLOGIA DESCOMPLICADA PARA JOVENS
// CAPÍTULO II - A IGREJA TEM UM PROPÓSITO?
// ============================================

window.dadosLicao = {
    titulo: "📖 CAPÍTULO II - A IGREJA TEM UM PROPÓSITO?",
    subtitulo: "Teologia Descomplicada para Jovens - Capítulo 2",
    mapaConfig: {
      centro: [31.0461, 34.8516],
      zoom: 6
    },
  
    listaAparicao: [
      // Capítulo II – Página de Abertura (pág. 23)
      { numero: 1, referencia: "", tags: "", topico: "📂 Capítulo II", pagina: 23, id: "" },
      
      // 1. Qual é o verdadeiro propósito da Igreja?
      { numero: 2, referencia: "Efésios 3.10", tags: "igreja / propósito / manifestação da sabedoria", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Versículo-Chave", pagina: 24, id: "ef3.10" },
      { numero: 3, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Ideia Central", pagina: 24, id: "" },
      { numero: 4, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Explicação Simples e Profunda", pagina: 24, id: "" },
      { numero: 5, referencia: "", tags: "adoração", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / a) A Igreja existe para adorar a Deus acima de tudo", pagina: 24, id: "" },
      { numero: 6, referencia: "Atos 2.47", tags: "adoração / louvor / igreja primitiva", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / a) A Igreja existe para adorar a Deus acima de tudo", pagina: 24, id: "at2.47" },
      { numero: 7, referencia: "João 4.23", tags: "adoração / espírito / verdade", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / a) A Igreja existe para adorar a Deus acima de tudo", pagina: 24, id: "jo4.23" },
      { numero: 8, referencia: "", tags: "edificação", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / b) A Igreja existe para edificar os crentes na fé", pagina: 24, id: "" },
      { numero: 9, referencia: "Efésios 4.12", tags: "edificação / ministério / corpo de Cristo", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / b) A Igreja existe para edificar os crentes na fé", pagina: 25, id: "ef4.12" },
      { numero: 10, referencia: "1 Coríntios 14.26", tags: "edificação / dons / comunhão", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / b) A Igreja existe para edificar os crentes na fé", pagina: 25, id: "1co14.26" },
      { numero: 11, referencia: "", tags: "evangelismo / missão", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / c) A Igreja existe para anunciar o evangelho", pagina: 25, id: "" },
      { numero: 12, referencia: "Mateus 28.19-20", tags: "grande comissão / discipulado / missão", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / c) A Igreja existe para anunciar o evangelho", pagina: 25, id: "mt28.19-20" },
      { numero: 13, referencia: "Atos 1.8", tags: "testemunhas / poder / Espírito Santo", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / c) A Igreja existe para anunciar o evangelho", pagina: 25, id: "at1.8" },
      { numero: 14, referencia: "", tags: "testemunho / luz do mundo", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / d) A Igreja existe para viver como testemunho visível", pagina: 25, id: "" },
      { numero: 15, referencia: "Mateus 5.13-14", tags: "sal da terra / luz do mundo / testemunho", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / d) A Igreja existe para viver como testemunho visível", pagina: 25, id: "mt5.13-14" },
      { numero: 16, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Perguntas Rápidas dentro da Explicação", pagina: 25, id: "" },
      { numero: 17, referencia: "Mateus 5.13-14", tags: "sal / luz / testemunho visível", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Perguntas Rápidas dentro da Explicação", pagina: 25, id: "mt5.13-14" },
      
      // Exemplos e ilustrações (págs. 26–27)
      { numero: 18, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Exemplo Didático", pagina: 26, id: "" },
      { numero: 19, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Exemplo Atual", pagina: 26, id: "" },
      { numero: 20, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Toque de Sabedoria", pagina: 26, id: "" },
      { numero: 21, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Você Sabia?", pagina: 26, id: "" },
      { numero: 22, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / História Ilustrativa – Quando a fé se torna missão", pagina: 26, id: "" },
      { numero: 23, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Palavra Pastoral", pagina: 27, id: "" },
      { numero: 24, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Aplicação Prática – Marque suas Respostas", pagina: 27, id: "" },
      { numero: 25, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Tarefa Simples para o Coração", pagina: 27, id: "" },
      { numero: 26, referencia: "", tags: "", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Espaço para Resposta", pagina: 28, id: "" },
      
      // 2. Qual é a missão da Igreja no mundo?
      { numero: 27, referencia: "Mateus 5.14", tags: "luz do mundo / cidade sobre o monte / missão", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Versículo-Chave", pagina: 29, id: "mt5.14" },
      { numero: 28, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Ideia Central", pagina: 29, id: "" },
      { numero: 29, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Explicação Simples e Profunda", pagina: 29, id: "" },
      { numero: 30, referencia: "", tags: "influência / valores do Reino", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / a) Influenciar a sociedade com valores do Reino", pagina: 29, id: "" },
      { numero: 31, referencia: "Mateus 5.16", tags: "boas obras / glorificar / luz", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / a) Influenciar a sociedade com valores do Reino", pagina: 29, id: "mt5.16" },
      { numero: 32, referencia: "", tags: "intercessão / oração", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / b) Interceder pelo mundo", pagina: 30, id: "" },
      { numero: 33, referencia: "1 Timóteo 2.1", tags: "oração / intercessão / autoridades", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / b) Interceder pelo mundo", pagina: 30, id: "1tm2.1" },
      { numero: 34, referencia: "", tags: "paz / reconciliação", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / c) Promover a paz e a reconciliação", pagina: 30, id: "" },
      { numero: 35, referencia: "Mateus 5.9", tags: "pacificadores / filhos de Deus / paz", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / c) Promover a paz e a reconciliação", pagina: 30, id: "mt5.9" },
      { numero: 36, referencia: "2 Coríntios 5.18-19", tags: "reconciliação / ministério / embaixadores", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / c) Promover a paz e a reconciliação", pagina: 30, id: "2co5.18-19" },
      { numero: 37, referencia: "", tags: "esperança / crises", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / d) Levar esperança em meio às crises", pagina: 30, id: "" },
      { numero: 38, referencia: "João 16.33", tags: "paz / tribulação / vitória", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / d) Levar esperança em meio às crises", pagina: 30, id: "jo16.33" },
      { numero: 39, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Perguntas Rápidas dentro da Explicação", pagina: 31, id: "" },
      { numero: 40, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Exemplo Didático", pagina: 31, id: "" },
      { numero: 41, referencia: "Mateus 5.13", tags: "sal da terra / preservar / sabor", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Exemplo Didático", pagina: 31, id: "mt5.13" },
      { numero: 42, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Exemplo Atual", pagina: 31, id: "" },
      { numero: 43, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Toque de Sabedoria", pagina: 31, id: "" },
      { numero: 44, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Você Sabia?", pagina: 32, id: "" },
      { numero: 45, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / História Ilustrativa – A Igreja que Alcança o Mundo", pagina: 32, id: "" },
      { numero: 46, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Palavra Pastoral", pagina: 32, id: "" },
      { numero: 47, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Aplicação Prática – Marque suas Respostas", pagina: 33, id: "" },
      { numero: 48, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Tarefa Simples para o Coração", pagina: 33, id: "" },
      { numero: 49, referencia: "", tags: "", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Espaço para Resposta", pagina: 33, id: "" },
      
      // 3. Como a Igreja cuida do crescimento espiritual dos membros?
      { numero: 50, referencia: "Efésios 4.11-12", tags: "dons / ministério / edificação", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Versículo-Chave", pagina: 34, id: "ef4.11-12" },
      { numero: 51, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Ideia Central", pagina: 34, id: "" },
      { numero: 52, referencia: "Atos 2.42-47", tags: "igreja primitiva / comunhão / discipulado", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Ideia Central", pagina: 34, id: "at2.42-47" },
      { numero: 53, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Explicação Simples e Profunda", pagina: 34, id: "" },
      { numero: 54, referencia: "", tags: "ensino / Palavra", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / a) Por meio do ensino da Palavra", pagina: 34, id: "" },
      { numero: 55, referencia: "2 Timóteo 3.16", tags: "inspiração / ensino / correção", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / a) Por meio do ensino da Palavra", pagina: 34, id: "2tm3.16" },
      { numero: 56, referencia: "Mateus 4.4", tags: "pão / palavra de Deus / viver", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / a) Por meio do ensino da Palavra", pagina: 34, id: "mt4.4" },
      { numero: 57, referencia: "", tags: "comunhão / partilha", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / b) Por meio da comunhão entre os irmãos", pagina: 35, id: "" },
      { numero: 58, referencia: "Gálatas 6.2", tags: "carregar cargas / lei de Cristo", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / b) Por meio da comunhão entre os irmãos", pagina: 35, id: "gl6.2" },
      { numero: 59, referencia: "Romanos 12.15", tags: "alegrar / chorar / empatia", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / b) Por meio da comunhão entre os irmãos", pagina: 35, id: "rm12.15" },
      { numero: 60, referencia: "", tags: "discipulado / disciplina", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / c) Por meio do discipulado e da disciplina", pagina: 35, id: "" },
      { numero: 61, referencia: "Mateus 28.19-20", tags: "discipulado / ensino / batismo", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / c) Por meio do discipulado e da disciplina", pagina: 35, id: "mt28.19-20" },
      { numero: 62, referencia: "Hebreus 12.11", tags: "disciplina / paz / justiça", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / c) Por meio do discipulado e da disciplina", pagina: 35, id: "hb12.11" },
      { numero: 63, referencia: "", tags: "dons / serviços", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / d) Por meio dos dons e serviços", pagina: 35, id: "" },
      { numero: 64, referencia: "1 Coríntios 12.7", tags: "dons / utilidade / bem comum", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / d) Por meio dos dons e serviços", pagina: 35, id: "1co12.7" },
      { numero: 65, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Perguntas Rápidas dentro da Explicação", pagina: 35, id: "" },
      { numero: 66, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Exemplo Didático", pagina: 36, id: "" },
      { numero: 67, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Exemplo Atual", pagina: 36, id: "" },
      { numero: 68, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Toque de Sabedoria", pagina: 36, id: "" },
      { numero: 69, referencia: "1 Pedro 2.2", tags: "leite espiritual / crescimento / salvação", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Você Sabia?", pagina: 36, id: "1pe2.2" },
      { numero: 70, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / História Ilustrativa – Crescendo Juntos na Fé", pagina: 36, id: "" },
      { numero: 71, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Palavra Pastoral", pagina: 37, id: "" },
      { numero: 72, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Aplicação Prática – Marque suas Respostas", pagina: 37, id: "" },
      { numero: 73, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Tarefa Simples para o Coração", pagina: 37, id: "" },
      { numero: 74, referencia: "", tags: "", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Espaço para Resposta", pagina: 38, id: "" },
      
      // 4. Evangelização é obrigação só de alguns ou de todos?
      { numero: 75, referencia: "Atos 1.8", tags: "testemunhas / poder / Espírito Santo", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Versículo-Chave", pagina: 39, id: "at1.8" },
      { numero: 76, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Ideia Central", pagina: 39, id: "" },
      { numero: 77, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Explicação Simples e Profunda", pagina: 39, id: "" },
      { numero: 78, referencia: "", tags: "obediência / mandamento", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / a) Evangelizar é obediência ao mandamento de Cristo", pagina: 39, id: "" },
      { numero: 79, referencia: "Mateus 28.19-20", tags: "grande comissão / mandamento / discipulado", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / a) Evangelizar é obediência ao mandamento de Cristo", pagina: 39, id: "mt28.19-20" },
      { numero: 80, referencia: "", tags: "gratidão / salvação", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / b) Evangelizar é um ato de gratidão pela salvação recebida", pagina: 40, id: "" },
      { numero: 81, referencia: "Atos 4.20", tags: "testemunhar / não posso calar / visto e ouvido", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / b) Evangelizar é um ato de gratidão pela salvação recebida", pagina: 40, id: "at4.20" },
      { numero: 82, referencia: "", tags: "responsabilidade / todo crente", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / c) Evangelizar é responsabilidade de todo crente", pagina: 40, id: "" },
      { numero: 83, referencia: "", tags: "amor ao próximo", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / d) Evangelizar é expressão de amor ao próximo", pagina: 40, id: "" },
      { numero: 84, referencia: "1 Coríntios 9.16", tags: "anunciar / obrigação / ai de mim", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / d) Evangelizar é expressão de amor ao próximo", pagina: 40, id: "1co9.16" },
      { numero: 85, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Perguntas Rápidas dentro da Explicação", pagina: 40, id: "" },
      { numero: 86, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Exemplo Didático", pagina: 41, id: "" },
      { numero: 87, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Exemplo Atual", pagina: 41, id: "" },
      { numero: 88, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Toque de Sabedoria", pagina: 41, id: "" },
      { numero: 89, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Você Sabia?", pagina: 41, id: "" },
      { numero: 90, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / História Ilustrativa – Uma Missão para Todos", pagina: 42, id: "" },
      { numero: 91, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Palavra Pastoral", pagina: 42, id: "" },
      { numero: 92, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Aplicação Prática – Marque suas Respostas", pagina: 43, id: "" },
      { numero: 93, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Tarefa Simples para o Coração", pagina: 43, id: "" },
      { numero: 94, referencia: "", tags: "", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / Espaço para Resposta", pagina: 43, id: "" }
    ],
  
    listaAlfabetica: [
      { referencia: "1 Co 9.16", tags: "anunciar / obrigação / ai de mim", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / d) Evangelizar é expressão de amor ao próximo", pagina: 40, id: "1co9.16" },
      { referencia: "1 Co 12.7", tags: "dons / utilidade / bem comum", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / d) Por meio dos dons e serviços", pagina: 35, id: "1co12.7" },
      { referencia: "1 Co 14.26", tags: "edificação / dons / comunhão", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / b) A Igreja existe para edificar os crentes na fé", pagina: 25, id: "1co14.26" },
      { referencia: "1 Pe 2.2", tags: "leite espiritual / crescimento / salvação", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Você Sabia?", pagina: 36, id: "1pe2.2" },
      { referencia: "1 Tm 2.1", tags: "oração / intercessão / autoridades", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / b) Interceder pelo mundo", pagina: 30, id: "1tm2.1" },
      { referencia: "2 Co 5.18-19", tags: "reconciliação / ministério / embaixadores", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / c) Promover a paz e a reconciliação", pagina: 30, id: "2co5.18-19" },
      { referencia: "2 Tm 3.16", tags: "inspiração / ensino / correção", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / a) Por meio do ensino da Palavra", pagina: 34, id: "2tm3.16" },
      { referencia: "At 1.8", tags: "testemunhas / poder / Espírito Santo", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / c) A Igreja existe para anunciar o evangelho", pagina: 25, id: "at1.8" },
      { referencia: "At 2.42-47", tags: "igreja primitiva / comunhão / discipulado", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Ideia Central", pagina: 34, id: "at2.42-47" },
      { referencia: "At 2.47", tags: "adoração / louvor / igreja primitiva", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / a) A Igreja existe para adorar a Deus acima de tudo", pagina: 24, id: "at2.47" },
      { referencia: "At 4.20", tags: "testemunhar / não posso calar / visto e ouvido", topico: "📂 Capítulo II / 4. Evangelização é obrigação só de alguns ou de todos? / b) Evangelizar é um ato de gratidão pela salvação recebida", pagina: 40, id: "at4.20" },
      { referencia: "Ef 3.10", tags: "igreja / propósito / manifestação da sabedoria", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / Versículo-Chave", pagina: 24, id: "ef3.10" },
      { referencia: "Ef 4.11-12", tags: "dons / ministério / edificação", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / Versículo-Chave", pagina: 34, id: "ef4.11-12" },
      { referencia: "Ef 4.12", tags: "edificação / ministério / corpo de Cristo", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / b) A Igreja existe para edificar os crentes na fé", pagina: 25, id: "ef4.12" },
      { referencia: "Gl 6.2", tags: "carregar cargas / lei de Cristo", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / b) Por meio da comunhão entre os irmãos", pagina: 35, id: "gl6.2" },
      { referencia: "Hb 12.11", tags: "disciplina / paz / justiça", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / c) Por meio do discipulado e da disciplina", pagina: 35, id: "hb12.11" },
      { referencia: "Jo 16.33", tags: "paz / tribulação / vitória", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / d) Levar esperança em meio às crises", pagina: 30, id: "jo16.33" },
      { referencia: "Jo 4.23", tags: "adoração / espírito / verdade", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / a) A Igreja existe para adorar a Deus acima de tudo", pagina: 24, id: "jo4.23" },
      { referencia: "Mt 28.19-20", tags: "grande comissão / discipulado / missão", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / c) A Igreja existe para anunciar o evangelho", pagina: 25, id: "mt28.19-20" },
      { referencia: "Mt 4.4", tags: "pão / palavra de Deus / viver", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / a) Por meio do ensino da Palavra", pagina: 34, id: "mt4.4" },
      { referencia: "Mt 5.13", tags: "sal da terra / preservar / sabor", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Exemplo Didático", pagina: 31, id: "mt5.13" },
      { referencia: "Mt 5.13-14", tags: "sal da terra / luz do mundo / testemunho", topico: "📂 Capítulo II / 1. Qual é o verdadeiro propósito da Igreja? / d) A Igreja existe para viver como testemunho visível", pagina: 25, id: "mt5.13-14" },
      { referencia: "Mt 5.14", tags: "luz do mundo / cidade sobre o monte / missão", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / Versículo-Chave", pagina: 29, id: "mt5.14" },
      { referencia: "Mt 5.16", tags: "boas obras / glorificar / luz", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / a) Influenciar a sociedade com valores do Reino", pagina: 29, id: "mt5.16" },
      { referencia: "Mt 5.9", tags: "pacificadores / filhos de Deus / paz", topico: "📂 Capítulo II / 2. Qual é a missão da Igreja no mundo? / c) Promover a paz e a reconciliação", pagina: 30, id: "mt5.9" },
      { referencia: "Rm 12.15", tags: "alegrar / chorar / empatia", topico: "📂 Capítulo II / 3. Como a Igreja cuida do crescimento espiritual dos membros? / b) Por meio da comunhão entre os irmãos", pagina: 35, id: "rm12.15" }
    ]
  };